sudo: required
services:
  - docker

before_install:
  - docker build -t sandergit180/potto-client-test -f ./client/Dockerfile.dev ./

script:
  - docker run -e CI=true sandergit180/potto-client-test npm test -- --coverage
 
after_success:
  - docker build -t sandergit180/potto-client -f ./client/Dockerfile.dev ./
  #- docker build -t sandergit180/potto-back ./potto

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push it to Docker Hub
  - docker push sandergit180/potto-client
 # - docker push sandergit180/potto-back
 # PUSH TO DOCKERHUB