apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: backend
    template:
        metadata:
            labels:
                component: backend
        spec:
            containers:
                -   name: backend
                    image: sandergit180/potto-back
                    ports:
                        - containerPort: 8000
                    env:
                        - name: PGUSER
                          value: postgres
                        - name: PGHOST
                          value: postgres-cluster-ip-service
                        - name: PGPORT
                          value: '5432'
                        - name: PGDATABASE
                          value: postgres
                        - name: POSTGRES_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: pgpassword
                              key: PGPASSWORD